repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: end-of-file-fixer
#      - id: check-added-large-files

  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3.8

#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.9.2
#    hooks:
#      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        types: [python]
